### ISSUE TITLE
Naming conflicts

### ISSUE THREAD

**Issue by lishoulong** [antfu/ni#33]
After install `ni` globally, I found nrm instruction is substituted by `ni` feature.
Usually, I use [nrm](https://www.npmjs.com/package/nrm) as managing npm registries tools.

So, can we rename nrm to other  name? From the download size of nrm, it was commonly used.

**Comment by lishoulong** [comment]
After search [solutions](https://github.com/npm/npm/issues/9040) for this problem, there is no good answer. 
The `npm` official solutions is to warning the developers for the conflicts, and let the owner to rename the exported bin name.

**Comment by ChasLui** [comment]
Is it possible to take a page from python virtual env and enter a proprietary env environment

**Comment by O2O4** [comment]
hahaha  , i alse make this problem
![image](https://user-images.githubusercontent.com/15516756/141825549-29de8bca-316b-45a0-be0b-3937a1af5b14.png)

**Comment by Bittttter** [comment]
I can't install `ni` where I had installed `nrm` before 😓.
The error log followed:

```bash
52 verbose argv "/Users/edz/.nvm/versions/node/v16.13.0/bin/node" "/Users/edz/.nvm/versions/node/v16.13.0/bin/npm" "i" "-g" "@antfu/ni"
53 verbose node v16.13.0
54 verbose npm  v8.1.0
55 error code EEXIST
56 error path /Users/edz/.nvm/versions/node/v16.13.0/bin/nrm
57 error EEXIST: file already exists
58 error File exists: /Users/edz/.nvm/versions/node/v16.13.0/bin/nrm
59 error Remove the existing file and try again, or run npm
60 error with --force to overwrite files recklessly.
61 verbose exit 1
```

**Comment by bowencool** [comment]
> Anyone knows a better way to solve this? Frankly, any cli names could potentially conflict with others. I would like to have something like "optional binary" for npm and let users select which cli they want or not.

`nrv` or `nui`?

**Comment by bowencool** [comment]
for me, 
``` bash
mv /usr/local/bin/nrm /usr/local/bin/nrt
npm i -g @antfu/ni
```

**Comment by yuri-scarbaci-lenio** [comment]
Something somewhat related is `nx`

the command `nx` to run a script is conflicting with the `nx` command from the [`nx` mono-repo tool](https://nx.dev/getting-started/intro)

Would you consider adding an alias to the `nx` command?
we have `nx` installed as a dev dependency in our project so this is not really breaking anything nor requires any direct change, but it gets confusing pretty fast to find scripts in the package.json running `nx something` to have to consider that it will be scoped with the nx monorepo tool instead of @antfu/ni tool ( even more confusing since they are both used to execute a shell command, but @antfu/ni does it without interacting with mono-repo logic, while nx run it scoped to the mono-repo packages )

I do understand it's impossible to avoid collission with ALL the CLI tools out there, but NX is a pretty big one and might be worth considering 🤔

**Comment by sschneider-ihre-pvs** [comment]
`nx` conflicts with https://nx.dev/
