### ISSUE TITLE
`nx` behaviors different with `npx` 

### ISSUE THREAD

**Issue by TooBug** [antfu/ni#42]
`npx` will try to load local package bins from `./node_modules/.bin`, if not match, then download (to tmp dir?) and execute.

`nx` seems skipped the search on local package bins, it will always download (to tmp dir?) and execute. For some packages, the results is different as well.

```sh
# install
ni -D jest ts-jest

# run
nx ts-jest config:init
```

I am using pnpm, the echo is like this:

```
Progress: resolved 11, reused 7, downloaded 2, added 0
......
```

But if run `npx ts-jest config:init`, it just run, without an extra installation.

**Comment by antfu** [comment]
in pnpm, `nx` is for [`pnpm dlx`](https://pnpm.io/cli/dlx). What we do is simple redirect. I guess you might keep using npx if you want it's behaviour.

**Comment by TooBug** [comment]
I think this worth rethinking.

In my opinion, `ni` package should try to have behavior in same command. So may be `pnpm exec` is better for `nx`, The name of `nx` in `README.md` is also `execute`.

Further more, maybe `ni` also needs a RFC to explain its behavior, since the deeper it goes, the more differences will show. 

Take `nx` as example, which behavior is intend by you?

1. run local package bin.
2. run global package bin.
3. download and run package bin.
4. try 1->2->3

No matter what command `ni` redirects to, the behavior between package managers are different. But `ni` has chance to take over and offer the same behavior (with many workarounds.)

**Comment by antfu** [comment]
> In my opinion, ni package should try to have same behavior in same command

That really deps on how you define "same behavior" - as you mentioned, behaviors between package managers are different. like I run `npm i` and `yarn install`, they are just doing similar but essentially, different things. It is not, and can not be the responsibility of ni to ease out the differences (it will always be a thin redirection layer). In the readme, it's already very clear what commands will be mapped to and I don't think RFCs are needed in this case.

I think it's valid to bring up the possible option for `pnpm exec` - but since we already pick up the `dlx` path for `nx` and it still has the clear and defined behavior, I don't think there is any problem with the choice. Meanwhile, as a side note, if you aim to run local packages, I think `npx` will already work fine no matter you are in `yarn` or `pnpm` project.

**Comment by MarvinXu** [comment]
Kind of ran into a similar confusion here... I just started using pnpm and not familiar with `dlx`.

In my case, I first installed parcel locally and then ran `nx parcel index.html`. Since 'x' is for 'execute' (same statement in the README), so I took it for granted that it should execute the locally installed command `parcel` . Instead it took a lot of time downloading every time I ran this. Maybe `dlx` stands for _download and execute_?

FYI.
