### ISSUE TITLE
Some thoughts on `nrm` and other naming conflicts

### ISSUE THREAD

**Issue by muzaisimao** [antfu/ni#66]
First of all, thank you very much for this project, it has been very convenient for me, but of course I also encountered the problem of `nrm` naming conflicts, whenever I want to uninstall a package, I still need to determine the current package manager, considering how often `npm uninstall` is used, I think I need to discuss this issue.

When I read #33, my first thought was to customize the alias in `.nirc`, but that didn't seem to work when I tried to dynamically generate the bin file. 
idea: read the configuration before install and generate the bin file, add it to `directories.bin`.

Reference:

 - `preinstall`: https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts

 - `directories.bin`: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#directoriesbin

 - `bin-links`: https://github.com/npm/bin-links

 - Similar Questions: https://stackoverflow.com/questions/67665230/can-i-add-files-to-directories-bin-dynamically-through-npm-script-before-npm-pro

After I researched and tried the above options with no results, I had to post the question to the community for further discussion.

If there is no other solution, is it possible to change `nrm` to `nun` or some other name ...😂...

**Comment by HongxuanG** [comment]
I agree

**Comment by MarkLyck** [comment]
@antfu I've seen the closed tickets and comments regarding `nrm` and it makes sense why you removed it due to conflicts.

But was there ever a replacement? How do I remove a package with `ni`??? I can't find a working command for it anywhere.

I don't even mind it being a long command, anything beats checking the package manager used manually and typing `pnpm remove xxx`

**Comment by muzaisimao** [comment]
Changed to `nun`, see #69 .
